packages:
  - name: Budget Package
    price: 99
    items:
      - eBook cover
      - Paperback / Hardback cover
      - Artwork without title
      - PNG typography title
      - 3D Mockups of book cover

  - name: Standard Package
    price: 149
    items:
      - eBook cover
      - Paperback / Hardback cover
      - Artwork without title
      - PNG typography title
      - 3D Mockups of book cover
      - Bookmark
      - Social media banner

  - name: Premium Package
    price: 199
    items:
      - eBook cover
      - Paperback / Hardback cover
      - Artwork without title
      - PNG typography title
      - 3D Mockups of book cover
      - Bookmark
      - Social media banner
      - 1 Character

  - name: Exclusive Package
    price: 279
    items:
      - eBook cover
      - Paperback / Hardback cover
      - Artwork without title
      - PNG typography title
      - 3D Mockups of book cover
      - Bookmark
      - Social media banner
      - 2 Characters
      - IG promo


other:
  - name: Character Design
    items:
      - name: Half body character
        price: 59
      - name: Full body character
        price: 99
  - name: Packages
    items:
      - name: Ten characters half body
        price: 479
      - name: Ten characters full body
        price: 699
  - name: NSFW
    items:
      - name: Two characters
        price: 149
      - name: Three characters
        price: 199
      - name: four characters
        price: 249
  - name: NSFW
    items:
      - name: Male single
        price: 99
      - name: Female single
        price: 99
      - name: Creatures
        price: 129